# Generated by Django 6.1.1 on 2026-09-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='yahyerh01@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(default='https://github.com/progdatatofa/progdatatofa.git'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default='https://github.com/progdatatofa/progdatatofa.git'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='09061678794', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(),
        ),
    ]
